import { writeFileSync, readdirSync } from 'node:fs';
import path, { extname, join } from 'node:path';
import { dedent } from 'ts-dedent';

import { getLatestVersionBatch } from 'fast-npm-meta';

import { createRequire } from 'node:module';
import type { FoolModule } from '../src';

const require = createRequire(import.meta.url);

const rNormalizeNpmName = /[/\-.]/g;

function normalizeNpm(name: string) {
  return name
    .replaceAll('@', '')
    .replaceAll(rNormalizeNpmName, '_');
}

(async () => {
  const allModuleFiles = readdirSync(path.resolve(__dirname, '../src/modules'))
    .filter(f => extname(f) === '.ts' && f[0] !== '_');

  writeFileSync(
    path.join(__dirname, '../src/modules/_.ts'),
    dedent`
      // This file is auto-generated by scripts/codegen.ts. Do not edit this file directly.
      /* eslint-disable @stylistic/comma-dangle -- codegen */
      import type { FoolModule } from './_types';

      export type { FoolModule };

      ${allModuleFiles.map(f => {
    const modName = f.slice(0, -3);
    return `import ${modName} from './${modName}';`;
  }).join('\n')}

      export const modules: Record<string, FoolModule> = {
        ${allModuleFiles.map(f => {
    const modName = f.slice(0, -3);
    return `${modName},`;
  }).join('\n')}
      };

    `
  );

  const allModules: FoolModule[] = Object.values(require('../src/modules/_.ts').modules);
  const ret: Record<string, string> = {
    ciallo: 'Ciallo～(∠・ω< )⌒☆'
  };

  const npmPackages = allModules.reduce<string[]>((acc, mod) => {
    if ('npm' in mod && mod.npm) {
      acc.push(mod.npm);
    }
    return acc;
  }, []);

  const metadatas = await getLatestVersionBatch(npmPackages);
  metadatas.forEach((metadata) => {
    if (metadata.version) {
      ret[normalizeNpm(metadata.name)] = metadata.version;
    }
  });

  const sortedRet = Object.keys(ret).sort().reduce<Record<string, string>>((acc, key) => {
    acc[key] = ret[key];
    return acc;
  }, {});

  writeFileSync(
    join(__dirname, '../src/modules/_version.json'),
    `${JSON.stringify(sortedRet, null, 2) || '{}'}\n`
  );
})();
