import { writeFileSync, readdirSync } from 'node:fs';
import path, { extname, join } from 'node:path';
import { asyncRetry } from 'foxts/async-retry';
import { dedent } from 'ts-dedent';

import { SingleBar, Presets } from 'cli-progress';

import { createRequire } from 'node:module';
import type { FoolModule } from '../src';

const require = createRequire(import.meta.url);

function normalizeNpm(name: string) {
  return name
    .replaceAll('@', '')
    .replaceAll('/', '_')
    .replaceAll('-', '_')
    .replaceAll('.', '_');
}

(async () => {
  const bar = new SingleBar({}, Presets.legacy);

  const allModuleFiles = readdirSync(path.resolve(__dirname, '../src/modules'))
    .filter(f => extname(f) === '.ts' && !f.startsWith('_'));

  writeFileSync(
    path.join(__dirname, '../src/modules/_.ts'),
    dedent`
      // This file is auto-generated by scripts/codegen.ts. Do not edit this file directly.
      /* eslint-disable @stylistic/comma-dangle -- codegen */
      import type { FoolModule } from './_types';

      export type { FoolModule };

      ${allModuleFiles.map(f => {
    const modName = f.slice(0, -3);
    return `import ${modName} from './${modName}';`;
  }).join('\n')}

      export const modules: Record<string, FoolModule> = {
        ${allModuleFiles.map(f => {
    const modName = f.slice(0, -3);
    return `${modName},`;
  }).join('\n')}
      };

    `
  );

  const allModules: FoolModule[] = Object.values(require('../src/modules/_.ts').modules);
  const ret: Record<string, string> = {
    ciallo: 'Ciallo～(∠・ω< )⌒☆'
  };

  bar.start(allModules.length, 0);

  await Promise.all(allModules.map(async (mod) => {
    if ('npm' in mod && mod.npm) {
      ret[normalizeNpm(mod.npm)] = await asyncRetry(() => fetch(`https://cdn.jsdelivr.net/npm/${mod.npm}/package.json`).then(res => res.json()).then(data => data.version));
    }
    bar.increment();
  }));

  bar.stop();

  const sortedRet = Object.keys(ret).sort().reduce<Record<string, string>>((acc, key) => {
    acc[key] = ret[key];
    return acc;
  }, {});

  writeFileSync(
    join(__dirname, '../src/modules/_version.json'),
    `${JSON.stringify(sortedRet, null, 2) || '{}'}\n`
  );
})();
